### ISSUE TITLE
Allow configuration for disabling syntax checking on save

### ISSUE THREAD

**Issue by jutley** [tsandall/vscode-opa#16]
Since I have VS Code configured to autosave files, every change I make cases syntax to be checked. I find this quite irritating as I use the integrated terminal, and each change navigates me away from that terminal.

It would be nice to be able to turn off the automatic syntax checking, and only run it when we want to.

**Comment by tsandall** [comment]
@jutley thanks for filing this! Sorry for the delayed response. KubeCon EU took up a bunch of my time. I've pushed a change to master that makes check-on-save optional and off-by-default. v0.2.3 of the extension will contain it.
