### ISSUE TITLE
Extension should offer to install the "opa" executable when it's not found

### ISSUE THREAD

**Issue by samridh90** [tsandall/vscode-opa#2]
Right now, it shows an error message asking the user to install the executable and ensure the $PATH is set correctly. 
A better UX would be to offer to install similar to how the vscode-go extension offer to and install missing go-tools (https://github.com/Microsoft/vscode-go/blob/master/src/goInstallTools.ts).

**Comment by samridh90** [comment]
I can open a PR for this if it makes sense having such a feature.

**Comment by samridh90** [comment]
This is turning out to be harder to implement than I expected.
Right now, I'm thinking about defining a new user setting in VS code called `opa.path`. Once the OPA binary is downloaded from Github releases, I'll set the `opa.path` setting to the path to which the binary was downloaded. If the user wants to move the package, they'd get a prompt to set `opa.path` to the correct path. The order of evaluation would be $PATH > opa.path. If `opa` is not found at $PATH, we'd offer to download `opa` and set `opa.path` after download.

**Comment by tsandall** [comment]
Adding an `opa.path` variable to the VS Code configuration sounds good to me.

**Comment by samridh90** [comment]
#4 opened to fix this
