### ISSUE TITLE
Bundle arg not picking up data files

### ISSUE THREAD

**Issue by thirkcircus** [tsandall/vscode-opa#23]
I don't know if this is an OPA bug or a vscode extension bug.  I'm on windows...

I'm trying to evaluate selection and it doesn't seem to be picking up _any_ data files.  Rego and input files are fine but data files (both yaml and json) are ignored.
Evaluating OPA at the command line works fine - data is used as part of evaluating the policy.

Afaict the vscode extension is sending
```
write-output "data" | opa eval --stdin --bundle file:///c%3A/some/dirs/rego --package mypkg --input file:///c%3A/some/dirs/rego/input.json
```
returns input and rego expressions

but if I try 
```
write-output "data" | opa eval --stdin --data file:///c%3A/some/dirs/rego --package mypkg --input file:///c%3A/some/dirs/rego/input.json
```
(note switch of `--bundle` for `--data` param) then I get all the data included in the expressions, as expected.

This means **evaluate selection** for anything in rego that depends on _data_ (anywhere down the stack) is failing to return results.

**Comment by patrick-east** [comment]
Out of curiosity, what are the data files called? What I'd like to rule out is whether or not this is an issue with the file/bundle loader code in OPA or if its a usability issue for us to address with the VSCode plugin.

Maybe something to clarify with the `--bundle` flag, it is treating the `file:///c%3A/some/dirs/rego` directory as the root of a bundle which means that only data files named `data.json` or `data.yaml` will be loaded. They are loaded with the same directory prefixing that happens with the `--data` flag, but it won't load any arbitrary JSON or YAML files now (which caused lots of headaches for anyone with a workspace containing say Kubernetes YAML manifests).

**Comment by thirkcircus** [comment]
> only data files named data.json or data.yaml will be loaded

right, so that's why!  
and it would seem there is no present way of telling vscode-opa to load an arbitrary data file, correct?

**Comment by thirkcircus** [comment]
also interesting...

if I name the file `data.yaml` it works as expected (thanks for the reply!) but naming it `data.yml` does not.

**Comment by patrick-east** [comment]
>and it would seem there is no present way of telling vscode-opa to load an arbitrary data file

That is correct, and yes it specifically look for `*.yaml`. The `--data` loader will actually just try to load _any_ file and if it successfully parses it as yaml or json it considers it valid.

To add some context on the reason this was done.. The arbitrary data file loading was/is causing huge problems for anyone with rego policies in a workspace that also includes other files. In particular for kubernetes projects where everything is a yaml manifest it is extremely painful (to the point that the vscode plugin is not even worth installing and it just constantly errors out).

What we've decided is that pushing more of the bundle rules will help to make some of the file naming and directory layout conventions more official by virtue of only loading data from them if they follow the bundle pattern. It should guide projects using rego to a more standard layout which makes additional tooling later on likely to work more smoothly. It also instantly makes mixed use projects more likely to work than they were before.

The downside is that projects like yours ran into incompatibilities and I'm making sure we update the documentation to explain more about how this works. What we would recommend is migrating to being able to use the bundle style files.

That being said there are a couple of changes coming up next (I'm working on them today) which will help for being able to specify which directories to load as bundles. It will also include a switch to disable bundle mode and go back to the older --data flag as a transitionary mode for projects like yours that abruptly stopped being able to evaluate policies.

**Comment by thirkcircus** [comment]
thanks, mine is a new project so I'm happy to just move forward with bundles.

however, having closed this issue, I've just noticed another problem which feels familiar (and is why I previously had to switch from windows to linux, I only moved back to running vscode on windows last week with the fixes to how vscode-opa treats windows file paths).

```
package test

this_does_not_work {
  data.foo == "bar"
}

but_this_does_work_sadpanda {
  data["c:"].Temp.rego.foo == "bar"
}
```

**Comment by patrick-east** [comment]
I'll look into it while I'm working on these other changes.. will include any fix required for that along with it.

**Comment by thirkcircus** [comment]
thanks, appreciated.  :)

**Comment by patrick-east** [comment]
@thirkcircus I believe that https://github.com/open-policy-agent/opa/pull/1813 should fix the issue with loading bundles with windows style paths.

The other vscode plugin changes are up here: https://github.com/tsandall/vscode-opa/pull/24

Thats pretty cool that WSL is working so well, I'll definitely have give that a try. I do most of my work on a macbook but side projects I do a on windows with my home desktop.
