### ISSUE TITLE
Filepath issue in Windows

### ISSUE THREAD

**Issue by PrasadJayakumar** [tsandall/vscode-opa#3]
I was not able to execute "OPA: Evaluate Package" command from VSCode Windows version.  I was getting
the following error

"open /d:/MYLOCALPATH/HelloWorld/input.json: The filename, directory name, or volume label syntax is incorrect."

There is an extra slash "/" which the command didn't like.  I happened to do a dirty fix, but served the purpose

Edited "extension.ts" line 215.  Did a substring(1).  Now it works.  

parseOPA('opa', editor.document.uri.path.**substring(1)**, (pkg: string, _: string[]) => {

Thought to report.  BTW, OPA is awesome.

**Comment by tsandall** [comment]
Thanks! I'll test this out and tag on your on the PR.

**Comment by tsandall** [comment]
Fixed in cbbc683954eee592614811d735383198d9324da3. I've published a new version of the extension to the marketplace (v0.0.3).
