### ISSUE TITLE
opa.path does not work on windows

### ISSUE THREAD

**Issue by jowe** [tsandall/vscode-opa#9]
I didn't manage to get opa.path to work on windows.
It looks to me that the command-exists module does not work for this usecase.

**Comment by tsandall** [comment]
Thanks for filing this. If you have a suggestion for how to resolve it, feel free to submit a PR or post here.

**Comment by usmanibnesadiq** [comment]
@jowe I had a lot of trouble with that as well but I resolved it by renaming the opa executable to only "opa.exe" and adding the path of executable to "PATH" environment variable. Or you can create a local settings file under .vscode folder and put this:
{
    "opa.path": "Drive:\\Folder_Containing_Opa.exe"
}
